version: "3.8"
networks:
  kafka-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 100.27.158.24:9094
  kafka1:
    container_name: kafka1
    image: telco_kafka:latest
    build:
      context: .
    ports:
        - "9192:9192"
        - "9094:9092"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.11
    volumes:
    - ./config/kafka1/server.properties:/kafka/config/server.properties
    - ./data/kafka1/:/data/kafka/
  kafka2:
    container_name: kafka2
    image: telco_kafka:latest
    build:
      context: .
    ports:
        - "9193:9192"
        - "9095:9092"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.12
    volumes:
    - ./config/kafka2/server.properties:/kafka/config/server.properties
    - ./data/kafka2/:/data/kafka/
  kafka3:
    container_name: kafka3
    image: telco_kafka:latest
    build:
      context: .
    ports:
        - "9194:9192"
        - "9096:9092"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.13
    volumes:
    - ./config/kafka3/server.properties:/kafka/config/server.properties
    - ./data/kafka3/:/data/kafka/

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    container_name: schema-registry
    depends_on:
      - kafka1
    ports:
      - "8081:8081"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.14
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9192
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
